[variables]
    NIXPACKS_PHP_ROOT = "webroot"
    COMPOSER_ALLOW_SUPERUSER = "1"

[phases.setup]
    nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
    cmds = ["composer install --no-dev --no-interaction --optimize-autoloader"]

[start]
    cmd = "php -S 0.0.0.0:$PORT -t webroot"
